### ISSUE TITLE
Plugin not work in 3.1.1 stable release

### ISSUE THREAD

**Issue by pixelpicosean** [IndicaInkwell/godot-ios-deploy#2]
It shows an error and seems like the version detecting is not right.

![error-dialog](https://cl.ly/3871130f1428/Image%202019-04-30%20at%203.57.53%20PM.png)
![error-log](https://cl.ly/e7a7b5fdf940/Image%202019-04-30%20at%203.59.53%20PM.png)

**Comment by PrestonKnopp** [comment]
Hey, sorry for the delayed response. I just merged the develop branch onto master which works with Godot 3.1.

Give master a try again and let me know if you need any assistance.

You can also download the release: https://github.com/PrestonKnopp/godot-ios-deploy/releases/tag/v0.1.0

I haven't worked on this in a while but I'm planning to after I finish up some work on another repo. There are still a lot of bugs, however, it is working.

**Comment by pixelpicosean** [comment]
Great, it loads but still throw some errors:
![error-log](https://cl.ly/2384381df619/Image%202019-05-04%20at%208.06.57%20PM.png)

**Comment by pixelpicosean** [comment]
Don't worry I've exported to iOS and use that xcode project successfully. Looking forward to improvements on this plugin, could be really useful for new Godot developers.

**Comment by PrestonKnopp** [comment]
The first error

> ... but active developer directory ... is a command line tools instance

can be fixed by running `xcode-select --reset`, unless you have set xcode path for a reason.

The second error does that for me, too, but then still deploys the app. I'll have to look into that.

> Don't worry I've exported to iOS and use that xcode project successfully

Okay, cool. I am planning to work on this soon. Stay tuned. Also, any other issues or suggestions please feel free to open an issue at any time. Thanks!
